name: Publish
on:
  push:
    branches:
      - master
jobs:
  Publish:
    name: Publish
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - run: git config --global user.email "53619745+rnbot@users.noreply.github.com"
      - run: git config --global user.name "React-Native-Windows Bot"
      - run: git remote set-url origin https://rnbot:${{ secrets.GITHUB_TOKEN }}@github.com/microsoft/react-native-tscodegen.git
      - run: yarn install --frozen-lockfile
      - run: yarn build
      - run: yarn test
      - run: npx beachball publish --branch master -n ${{ secrets.npmAuthToken }} -yes --bump-deps --access public
